<?php

declare(strict_types=1);

namespace App\Services\Ocr\Drivers;

use App\Contracts\Ocr\StartsDocumentOcr;
use App\Enums\DocumentProcessingStatus;
use App\Enums\ExtractionFieldSensitivity;
use App\Models\UploadedDocument;
use Illuminate\Support\Facades\Log;
use JsonException;

use function json_encode;

/**
 * POC / CI stand-in for a real OCR provider.
 * Returns deterministic structured extraction JSON so demos and tests stay stable offline.
 */
final class MockOcrExtractor implements StartsDocumentOcr
{
    /**
     * Build a fake extraction payload from the uploaded file metadata.
     * Does not call external APIs — safe without AWS credentials.
     */
    public function start(UploadedDocument $document): void
    {
        $extractedText = $this->buildExtractedText($document);

        $document->forceFill([
            'processing_status' => DocumentProcessingStatus::Completed,
            'extracted_text' => $extractedText,
            'processing_error' => null,
            'processing_finished_at' => now(),
            'textract_job_id' => null,
        ])->save();

        Log::info('OCR: mock driver completed extraction.', [
            'uploaded_document_id' => $document->id,
            'tenant_id' => $document->tenant_id,
            'original_filename' => $document->original_filename,
            'extracted_length' => mb_strlen($extractedText),
        ]);
    }

    /**
     * Kept for unit-level assertions that only need the payload.
     */
    public function extract(UploadedDocument $document): string
    {
        return $this->buildExtractedText($document);
    }

    private function buildExtractedText(UploadedDocument $document): string
    {
        $filename = $document->original_filename;
        $reference = 'MOCK-'.mb_strtoupper(mb_substr(hash('xxh3', $filename), 0, 8));

        try {
            return json_encode([
                'document_type' => 'other',
                'summary' => "Mock extraction for {$filename}",
                'fields' => [
                    [
                        'label' => 'Source file',
                        'value' => $filename,
                        'confidence' => 0.99,
                        'sensitivity' => null,
                    ],
                    [
                        'label' => 'Detected mime type',
                        'value' => $document->mime_type,
                        'confidence' => 0.98,
                        'sensitivity' => null,
                    ],
                    [
                        'label' => 'Document type',
                        'value' => 'identity / statement / other',
                        'confidence' => 0.95,
                        'sensitivity' => null,
                    ],
                    [
                        'label' => 'Reference',
                        'value' => $reference,
                        'confidence' => 0.97,
                        'sensitivity' => null,
                    ],
                    // Sample sensitive field so the extraction UI can demo masking offline.
                    [
                        'label' => 'BSN',
                        'value' => '123456789',
                        'confidence' => 0.91,
                        'sensitivity' => ExtractionFieldSensitivity::Bsn->value,
                    ],
                ],
                'tables' => [
                    [
                        'title' => 'File metadata',
                        'headers' => ['Field', 'Value'],
                        'rows' => [
                            [
                                'Approximate size (KB)',
                                (string) max(1, (int) round($document->size_bytes / 1024)),
                            ],
                        ],
                    ],
                ],
                'notes' => ['Generated by the mock OCR driver.'],
                'confidence' => 0.96,
            ], JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
        } catch (JsonException $exception) {
            return '{"document_type":null,"summary":null,"fields":[],"tables":[],"notes":[],"confidence":null}';
        }
    }
}
