<?php

declare(strict_types=1);

namespace App\Services\Ocr\Drivers;

use App\Contracts\Ocr\StartsDocumentOcr;
use App\Enums\DocumentProcessingStatus;
use App\Models\UploadedDocument;
use JsonException;

use function json_encode;

/**
 * POC / CI stand-in for a real OCR provider.
 * Returns deterministic structured extraction JSON so demos and tests stay stable offline.
 */
final class MockOcrExtractor implements StartsDocumentOcr
{
    /**
     * Build a fake extraction payload from the uploaded file metadata.
     * Does not call external APIs — safe without AWS credentials.
     */
    public function start(UploadedDocument $document): void
    {
        $extractedText = $this->buildExtractedText($document);

        $document->forceFill([
            'processing_status' => DocumentProcessingStatus::Completed,
            'extracted_text' => $extractedText,
            'processing_error' => null,
            'processing_finished_at' => now(),
            'textract_job_id' => null,
        ])->save();
    }

    /**
     * Kept for unit-level assertions that only need the payload.
     */
    public function extract(UploadedDocument $document): string
    {
        return $this->buildExtractedText($document);
    }

    private function buildExtractedText(UploadedDocument $document): string
    {
        $filename = $document->original_filename;
        $reference = 'MOCK-'.mb_strtoupper(mb_substr(hash('xxh3', $filename), 0, 8));

        try {
            return json_encode([
                'document_type' => 'other',
                'summary' => "Mock extraction for {$filename}",
                'fields' => [
                    ['label' => 'Source file', 'value' => $filename],
                    ['label' => 'Detected mime type', 'value' => $document->mime_type],
                    ['label' => 'Document type', 'value' => 'identity / statement / other'],
                    ['label' => 'Reference', 'value' => $reference],
                    ['label' => 'Confidence', 'value' => '0.97 (mock)'],
                ],
                'tables' => [
                    [
                        'title' => 'File metadata',
                        'headers' => ['Field', 'Value'],
                        'rows' => [
                            [
                                'Approximate size (KB)',
                                (string) max(1, (int) round($document->size_bytes / 1024)),
                            ],
                        ],
                    ],
                ],
                'notes' => ['Generated by the mock OCR driver.'],
            ], JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
        } catch (JsonException $exception) {
            return '{"document_type":null,"summary":null,"fields":[],"tables":[],"notes":[]}';
        }
    }
}
